//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_List
    {
        public int Item_id { get; set; }
        public string Item_Code { get; set; }
        public string Invent_Type { get; set; }
        public string Pref_Vendor { get; set; }
        public string Reorder_Point_Min { get; set; }
        public string Reorder_Point_Max { get; set; }
        public string Quantity_on_Hand { get; set; }
        public string Quantity_on_Order { get; set; }
        public string Quantity_on_Available { get; set; }
        public string Mark_up_Level { get; set; }
        public string Cost { get; set; }
        public string Item_Description { get; set; }
    }
}
